### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by Dean-Coakley** [JiaKunUp/jalpc_jekyll_theme#40]
Hi @JiaKunUp ,

Thank you so much for creating such a great Jekyll theme!

I want to completely remove the translation system. I only require English and it is a pain to have to update en.json as well as the other files too for every change. How can I go about this? Sorry for basic question, I have not used Jekyll before. Thanks.

**Comment by JiaKunUp** [comment]
Thanks for using this theme.

A simple way to remove language feature is just clearing `locals` folder and edit content in html files(`_includes/_sections/`), I think this will help you.

**Comment by Dean-Coakley** [comment]
Appears to be working as you say. 

Thank you very much! 👍 However this is giving a 404 error for not finding en.json. Is there an easy way to fix this?

**Comment by JiaKunUp** [comment]
You can remove `i18next.min.js` from _includes/index_head.html` and `localization.js` from `_includes/index_foot.html`

**Comment by JiaKunUp** [comment]
From this comment you can clear `_data/language.yml` to remove language. <https://github.com/JiaKunUp/jalpc_jekyll_theme/commit/d57316ae9577e8d71fce1cb929ddef669207b69b>

**Comment by Dean-Coakley** [comment]
Seems perfect now. Thank you so much!
