### ISSUE TITLE
gh-pages is rendering a text page. working fine on my local machine 

### ISSUE THREAD

**Issue by ashutoshmjain** [JiaKunUp/jalpc_jekyll_theme#42]
Hi all

I am new to github and jekyll (:-

I forked   'jalpc_jekyll_theme repository into a 'ashutoshmjain.homepage' repository. And then cloned it to my local machine. 

Made several changes. Everything looks good when I 'jekyll serve' on my localhost:4000

I then pushed the changes to git hub. The page https://ashutoshmjain.github.io/homepage appears text only page. 

I made sure to follow the instructions in README for the change in base url. Also removed the CNAME as github was throwing warnings. 

Will appreciate any help or pointers. 

Ashutosh

**Comment by JiaKunUp** [comment]
Thanks for using Jalpc jekyll theme.
Since your index page url is <https://ashutoshmjain.github.io/homepage> your need to change **baseurl** to `/homepage/`, all files are located based on this url.Please try it.

**Comment by ashutoshmjain** [comment]
Wow  - That worked  ..

Thanks a ton 

Keep up the good work :+1:
