### ISSUE TITLE
Social network

### ISSUE THREAD

**Issue by ritayadav** [JiaKunUp/jalpc_jekyll_theme#44]
Hello sir,

Please add more social network

**Comment by JiaKunUp** [comment]
Thanks for advice!
Now we have email, github and facebook, if you want to add more social network, you can edit **author** in `_config.yml` and add them in `_includes.html/sections/about.html`, all social network icons are in tag `<ul class="list-inline social-icon">`.

**Comment by ritayadav** [comment]
Thank you,  I did it.

**Comment by JiaKunUp** [comment]
Great! 👍 @ritayadav
