### ISSUE TITLE
Blog page - title behavior

### ISSUE THREAD

**Issue by ashutoshmjain** [JiaKunUp/jalpc_jekyll_theme#45]
Jack @JiaKunUp 

When I click on the button 'AmJ'  on the blog pages corner ..(top right corner ..same as Jalpc)   , it routs me to url 'ashutoshmjain.github.com' .. Since there is nothing hosted on above url , it returns a 404 error. 

Is there a way, I could have it routed to ashtoshmjain.github.com/homepage where my site is hosted ..

btw - it works fine on the main landing page where clicking on it takes me to page top .. 

Thanks in advance

**Comment by JiaKunUp** [comment]
@ashutoshmjain  Thanks for using this theme, this code is located at `_includes/header.html` and I use `<a class="navbar-brand" href="/">{{ site.title }}</a>` before, now it has changed to `<a class="navbar-brand" href="{{ site.url }}">{{ site.title }}</a>`, I think it works for you.
Thanks for finding this bug.

**Comment by ashutoshmjain** [comment]
It worked for me  .. 
Thanks again for the wonderful work . 
Really appreciate

Ashutosh
